asu_controller:

 joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50 
   
 position_controller:
   type: position_controllers/JointTrajectoryController
   joints:
     - J1
     - J2
     - J3
     - J4
     - J5
     
 gazebo_ros_control/pid_gains:
   J1: {p: 100.0, i: 0.1, d: 10.0}
   J2: {p: 100.0, i: 0.1, d: 10.0}
   J3: {p: 100.0, i: 0.1, d: 10.0}
   J4: {p: 100.0, i: 0.1, d: 10.0}
   J5: {p: 100.0, i: 0.1, d: 10.0}
   J6: {p: 100.0, i: 0.1, d: 10.0}
   
controller_list:
 - name: asu_controller/position_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - J1
     - J2
     - J3
     - J4
     - J5
   allowed_execution_duration_scaling: 1.2
   allowed_goal_duration_margin: 0.5
